FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    python3-gdal

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt 


EXPOSE 8000

# CMD ["python","manage.py","runserver","0.0.0.0:8000" ]
