# Generated by Django 5.1 on 2025-02-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipointdata',
            name='description',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygondata',
            name='city',
            field=models.CharField(default='city', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygondata',
            name='population',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
